import Head from 'next/head'

import { Container } from '@/components/Container'
import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>Aware: Terms of service</title>
        <meta
          name="description"
          content="Aware: Terms of service"
        />
      </Head>
      <Header />
      <main>

				<Container className="pt-20 pb-16 lg:pt-32">
					<div>
						<h2><strong>Aware Terms of Service &amp; Privacy Policy</strong></h2>
					</div>
					<p>These terms and conditions regulate all use of the useaware.co website and all content, services, and products accessible at or through the website, including, but not limited to, the useaware.co user management service ("Aware"), (taken together, the Services). Acceptance of these terms and conditions is required in order to use the Services. This Agreement comprises all operating rules, policies, and procedures that may be published from time to time on this Site by useaware.co (collectively, the "Agreement").Read this Agreement before accessing the Services. By accessing or using any part of the website, you agree to be bound by the terms and conditions of this agreement. If you do not agree to all the terms of this agreement, then you may not access the Services. If these terms and conditions are considered an offer by Aware, acceptance is expressly limited to these terms. The Services are not available to individuals who are younger than 18 years old.</p>
					<h1><strong>Your Aware Account.</strong></h1>
					<p>If you sign up for the Services, it is your responsibility to keep your account secure. You are responsible for all activities that occur under the account and any other actions taken in connection with the account. You must inform Aware immediately of any unauthorized use of your account or any other security breaches. Aware will not be held liable for any actions or omissions made by you, including any damages that may arise from such acts or omissions. You must be a human; accounts registered by automated methods, such as bots, are not allowed. You must provide your full legal name, a valid email address, and any other information requested in order to complete the sign-up process. You must not, in the use of the Services, violate any laws in your jurisdiction and in the United States of America (including but not limited to copyright or trademark laws).</p>
					<h1><strong>Privacy Policy.</strong></h1>
					<p>Aware ("Aware" or "We") is committed to protecting the privacy of visitors to the Aware website and users of the Aware service (the "Service"). This privacy policy (the "Policy) was prepared because we believe you (the "User") should know as much as possible about the personal information we collect about you, why we collect it, how we use it, and when we share it with third parties.Aware utilizes the personal data given by the User to operate and enable the Service, to enhance and personalize your experience with the Service, and to send you Service related updates, notices and announcements. We may also use that information to inform the User about our new products, services, updates and other Aware information we think the User may find to be of interest.Furthermore, this Policy clarifies your choices with respect to how we collect and use your information. You may exercise your choices about how we collect and use your information in line with this Policy at any time. Your continued use of the website (the "Website") and our services, signify your agreement to this Policy and any updates thereto.We are very mindful of the User's right to privacy regarding the information the User supplies to us. At Aware, our policy is to use the information exclusively to provide the User with better service. If you have any queries or concerns regarding this Privacy Policy, you are welcome to contact us as provided in the Privacy Policy.</p>
					<h1><strong>The Information We collect for our Service.</strong></h1>
					<h1>Aggregation of User Data.</h1>
					<p>Aware ("Aware" or "We") is committed to protecting the privacy of visitors to the Aware website and users of the Aware service (the "Service"). This privacy policy (the "Policy) was prepared because we believe you (the "User") should know as much as possible about the personal information we collect about you, why we collect it, how we use it, and when we share it with third parties.Aware utilizes the personal data given by the User to operate and enable the Service, to enhance and personalize your experience with the Service, and to send you Service related updates, notices and announcements. We may also use that information to inform the User about our new products, services, updates and other Aware information we think the User may find to be of interest.Furthermore, this Policy clarifies your choices with respect to how we collect and use your information. You may exercise your choices about how we collect and use your information in line with this Policy at any time. Your continued use of the website (the "Website") and our services, signify your agreement to this Policy and any updates thereto.We are very mindful of the User's right to privacy regarding the information the User supplies to us. At Aware, our policy is to use the information exclusively to provide the User with better service. If you have any queries or concerns regarding this Privacy Policy, you are welcome to contact us as provided in the Privacy Policy.</p>
					<h1>Usage Tracking Within The Aware Service.</h1>
					<p>Aware may collect and combine the information you provide with similar data gathered from other visitors to the Website or users of the Service in order to evaluate or enhance the Website or its Services. Aware may aggregate data to determine the usage patterns or interests of visitors to the Website or users of the Service, or for purposes related to the technical support or security of the Website and our computer systems. For example, we acquire traffic data that is regularly generated with Users' online activities such as IP addresses, the name of the website from which you entered our website, session durations, viewed pages, type of mobile device and computer operating system. We use all of this information to analyze trends among our Users to help improve our Website. The aggregated data that we assess, contains no personal information or other information that could identify an individual.</p>
					<h1>Cookies</h1>
					<p>Our Website employs "Cookies" to recognize the parts of our Website that you have visited. A Cookie is a small snippet of data stored on your computer or mobile device by your web browser. We use Cookies to customize the Content that you view on our Website. Most web browsers can be set to turn off the utilization of Cookies. However, if you deactivate Cookies, you may not be able to access certain features on our Website accurately or at all.</p>
					<h1>User information to Certain Third Parties</h1>
					<p>On occasion, Aware may provide generic usage data from our Products to our data suppliers for royalty-related purposes. This data will not include any personal details about individual users. We never sell any information that we collect from the Website to third parties. In certain cases, such as when it is necessary to protect our legal rights or in response to a court order, or in connection with a sale or merger of Aware or its assets, we may disclose information, including personal information, collected from the Website. Whenever possible, these disclosures will be subject to protective orders or confidentiality agreements. With respect to information collected in the course of our marketing activities, Aware may exchange business leads with our affiliates from time to time. Additionally, we may, on limited occasions, share your personal information with third-party marketing partners. These partners generally consist of persons or entities with whom we maintain a relationship and which offer certain complementary products and services to those Services that we offer. We will use commercially reasonable efforts to ensure that third parties protect your personal information. Additionally, you can ask us to stop sharing your personal information with these third parties, or to tell you who we shared it with, at any time. To make such requests, please follow the instructions provided concerning your personal information.</p>
					<h1>Receipt of Communications.</h1>
					<p>If you no longer wish to receive communications from us, you can update your Aware account to opt out. However, you may still receive certain communications from us if you or your organization requests them.</p>
					<h1>Server Security.</h1>
					<p>The Aware servers are physically secure and may only be accessed by Aware's technical or support personnel whose jobs specifically relate to maintaining the integrity of the Aware servers or supporting product-related functions. The individuals responsible for the security of the servers and the confidentiality of the information stored on them must take all reasonable and appropriate measures to secure personal information, such as encryption, limiting access, detecting unauthorized access, and not keeping the data longer than necessary.</p>
					<h1>Third Party Sites.</h1>
					<p>As a visitor to our Website or a subscriber to our Services, you may choose to visit a third party's website via links available on our Website. Although you may still see the Aware branding, you will be subject to that third-party's privacy policy, if one exists. We suggest you review the privacy policies of any third-party websites you visit. Aware is not liable for how that third-party may collect or use your personal information.</p>
					<h1><strong>Payment and Renewal.</strong></h1>
					<h1>General Terms.</h1>
					<p>Optional paid services, such as additional features, functionality, or capacity, can be obtained through the Services (any such services, an "Upgrade"). By selecting an Upgrade, you agree to pay Aware the indicated monthly or annual subscription fees for that service (additional payment terms are described below). Payments will be taken on a pre-pay basis on the day you sign up for an Upgrade and will cover the use of that service for the indicated monthly or annual subscription period. Upgrade fees are not eligible for refunds.</p>
					<h1>Automatic Renewal.</h1>
					<p>Unless you inform us before the end of the applicable subscription period that you wish to terminate an Upgrade, your Upgrade subscription will automatically renew and you permit us to charge the applicable annual or monthly subscription fee for such Upgrade (as well as any taxes) using any credit card or other payment method we have on file for you. Upgrades can be canceled at any time for any reason in the Settings area of your dashboard.</p>
					<h1>Fees and payment.</h1>
					<p>By signing up for an Aware account you agree to pay Aware the monthly fees indicated to you when you registered for the service in exchange for the Aware services. Fees will be charged from the day your paid account is created and before using the services. Aware reserves the right to modify the payment terms and fees with thirty (30) days written notice to you. You can cancel your Aware account whenever you want, but you must give Aware thirty (30) days written notice. Written notices must be given by email communication.</p>
					<h1>Support.</h1>
					<p>Aware includes access to email support. "Email support" means the ability to make requests for technical support by email at any time (with reasonable efforts by Aware to respond within three business days) concerning the use of Aware.</p>
					<h1><strong>Aware Platform.</strong></h1>
					<p>Any use of the Platform, including use of the Platform through a third-party product that accesses Aware, is bound by these Terms of Service plus the following specific terms:</p>
					<h1>Damage and liability.</h1>
					<p>Any use of the Platform, including use of the Platform through a third-party product that accesses Aware, is bound by these Terms of Service plus the following specific terms:</p>
					<ul role="list">
						<li>No one has been banned for using Aware, but we’re not responsible if this happens or if your account is suspended.</li>
						<li>Don't mix Aware with other LinkedIn tools that have similar functionality.</li>
						<li>We don’t sell your information to third parties.</li>
						<li>Aware is not affiliated with LinkedIn or any other third-parties.</li>
						<li>It is your own responsibility to comply with LinkedIn rules and any legislation that you are subject to.</li>
						<li>You use Aware at your own risk.</li>
						<li>We don’t guarantee specific outcomes from using Aware.</li>
						<li>We don’t guarantee the continuous, uninterrupted or error-free operation of the service.</li>
						<li>Please try Aware with our Free Trial, before purchasing the software.</li>
					</ul>
					<h1>Discontinuation.</h1>
					<p>Aware reserves the right at any time to modify or discontinue, temporarily or permanently, your access to the Platform (or any part thereof) with or without notice.</p>
					<h1>Marketing.</h1>
					<p>As a user, you give Aware a perpetual world-wide license to use your company's logos as well as your written feedback to us, unless Aware agrees in writing otherwise. These assets and logos will be used purely for marketing and sales efforts, such as being displayed on our website.</p>
					<h1>Copyright Infringement.</h1>
					<p>Aware requests that its intellectual property rights be respected, and in turn, it respects the intellectual property rights of others. If you feel that material found on or connected to by Aware infringes your copyright, you are urged to inform Aware. We will respond to all such notifications, including, if necessary or appropriate, by removing the infringing material or disabling all links to the material. If, under appropriate circumstances, it is established that a visitor is a repeat infringer of the copyrights or other intellectual property rights of Aware or others, Aware will terminate the visitor's access to and use of the Services. In such an instance, Aware will not be obligated to refund any amounts previously paid. By purchasing the service, you are confirming that you understand what you are buying and will not file a fraudulent dispute.</p>
					<h1>Intellectual Property.</h1>
					<p>This Agreement does not give you any rights to Aware or third party intellectual property, and all rights, title and interest in such property will stay (between the two parties) solely with Aware. The Aware logo, and all other trademarks, service marks, graphics and logos used in connection with Aware or the Services are trademarks or registered trademarks of Aware or its licensors. Other trademarks, service marks, graphics and logos used in connection with the Services may belong to other third parties. Your usage of the Services does not entitle you to reproduce or use any Aware or third-party trademarks.</p>
					<h1>User license.</h1>
					<p>Under this license you may not:Attempt to decompile or reverse engineer any software contained on Aware's web site or Platform.Access the Site or Services in order to build a similar or competitive service.This license shall automatically terminate if you violate any of these restrictions and may be terminated by Aware at any time.</p>
					<h1>Changes.</h1>
					<p>Aware reserves the right, at its sole discretion, to modify or replace any part of this Agreement. It is your responsibility to check this Agreement periodically for changes. Your continued use of or access to the Services following the posting of any changes to this Agreement constitutes acceptance of those changes. Aware may also, in the future, offer new services and/or features through the Services. These new features and/or services shall remain subject to the terms and conditions of this Agreement.</p>
					<h1>Termination.</h1>
					<p>Aware reserves the right to end your access to all or any part of the Services at any moment, with or without reason, with or without prior notification, taking effect immediately. If you want to finish this Agreement or your Aware account (if you have one), you can simply stop using the Services. Nevertheless, if you have a paid Aware account, it can only be terminated by Aware if you break this Agreement and fail to fix the breach within thirty (30) days from Aware's notification to you. Aware is able to terminate the Services immediately as part of a general shut down of our service. All provisions of this Agreement which should remain in effect after termination will remain in effect, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>
					<h1>Disclaimer of Warranties.</h1>
					<p>The Services are provided "as is". Aware and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither Aware nor its suppliers and licensors, makes any warranty that the Services will be free of errors or bugs, or that access to the Services will be continuous and/or uninterrupted. You understand that you download from, or otherwise obtain content or services through, the Services at your own discretion and risk.</p>
					<h1>Limitation of Liability.</h1>
					<p>Under no circumstances shall Aware, its suppliers, or licensors be held accountable in relation to any issue of this agreement, whether under a contract, negligence, strict liability, or any other legal or equitable theory, for: (i) any special, indirect, or consequential damages; (ii) the cost of obtaining substitute products or services; (iii) any interruption of usage or loss or corruption of data; or (iv) any amount that exceeds the fees paid by you to Aware in this agreement over the twelve (12) month period preceding the cause of action. Aware shall have no liability for any failure or delay due to matters outside of or not within their control. This shall not be applicable to the extent prohibited by applicable law.</p>
					<h1>Indemnification.</h1>
					<p>You agree to indemnify and hold Aware harmless, as well as its contractors, its licensors, and their respective directors, officers, employees and agents from and against any and all claims and expenses, including attorneys' fees, arising out of your use of the Services, including but not limited to your violation of this Agreement.</p>
					<h1>Entire Agreement.</h1>
					<p>This Agreement constitutes the entire agreement between Aware and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of Aware, or by the posting by Aware of a revised version.</p>
					<h1>Venue.</h1>
					<p>Except to the extent that applicable law, if any, provides otherwise, this Agreement, any access to or use of the Services will be governed by the laws of United States of America, excluding its conflict of law provisions, and the proper venue for any disputes arising out of or relating to any of the same will be the United States of America. Any legal action or arbitration shall take place in the United States of America, in the English language. The prevailing party in any action or proceeding to enforce this Agreement shall be entitled to costs and attorneys' fees.</p>
					<h1>Severability.</h1>
					<p>If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties' original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof.</p>
					<h1>Assignment.</h1>
					<p>You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; Aware may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.If you have questions about this Terms of Service &amp; Privacy Policy, please send those to support@useaware.co</p>
				</Container>

      </main>
      <Footer />
    </>
  )
}
